// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAbnZRpayJYaQTEYpSldpYDeCpNh-YOhQ',
    appId: '1:398897716420:web:32c899d331ef79e4123d91',
    messagingSenderId: '398897716420',
    projectId: 'dvij-flutter',
    authDomain: 'dvij-flutter.firebaseapp.com',
    storageBucket: 'dvij-flutter.appspot.com',
    measurementId: 'G-Y0GBXJ66W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7GAVkgBhwrL4Km6VyW9QBmFf88D7u1g',
    appId: '1:398897716420:android:35f49411212c68b8123d91',
    messagingSenderId: '398897716420',
    projectId: 'dvij-flutter',
    storageBucket: 'dvij-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB12R-4a7E5g-NG5hcbzu--T5cNm57Fmbg',
    appId: '1:398897716420:ios:894605b53ffda064123d91',
    messagingSenderId: '398897716420',
    projectId: 'dvij-flutter',
    storageBucket: 'dvij-flutter.appspot.com',
    iosBundleId: 'com.example.dvijFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB12R-4a7E5g-NG5hcbzu--T5cNm57Fmbg',
    appId: '1:398897716420:ios:db6fd6c8a00f7eeb123d91',
    messagingSenderId: '398897716420',
    projectId: 'dvij-flutter',
    storageBucket: 'dvij-flutter.appspot.com',
    iosBundleId: 'com.example.dvijFlutter.RunnerTests',
  );
}
